version: '3.4'

services:
  db:
    container_name: mariadb_10_11
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=change_me
      - MYSQL_USER=change_me
      - MYSQL_PASSWORD=change_me
    ports:
      - "3306:3306"
    command: mysqld --sql-mode="NO_ENGINE_SUBSTITUTION"
