version: '3.4'

services: 
    db:
        image: mariadb:10.3.7
        restart: always
        environment: 
            - MYSQL_ROOT_PASSWORD=root
        ports: 
            - "3306:3306"
    pma:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports: 
            - "8080:80"
        environment: 
            - PMA_HOST=db
        networks: 
            - mariadb_net
            - default

networks: 
    mariadb_net:
        external: true