services:
  nginx:
    image: nginx:1.29-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/conf.d:/etc/nginx/conf.d:ro"
      - "./config/sites-available:/etc/nginx/sites-available:ro"
      - "./config/sites-enabled:/etc/nginx/sites-enabled:ro"
      - "./data:/usr/share/nginx/html:ro"
      - "./logs:/var/log/nginx"
    restart: unless-stopped
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true